export const bussines = [
  { label: 'Engenheiro', value: 'engenheiro' },
  { label: 'Médico', value: 'medico' },
  { label: 'Advogado', value: 'advogado' },
  { label: 'Professor', value: 'professor' },
  { label: 'Arquiteto', value: 'arquiteto' },
  { label: 'Enfermeiro', value: 'enfermeiro' },
  { label: 'Psicólogo', value: 'psicologo' },
  { label: 'Desenvolvedor', value: 'desenvolvedor' },
  { label: 'Designer', value: 'designer' },
  { label: 'Analista de Sistemas', value: 'analista_sistemas' },
  { label: 'Farmacêutico', value: 'farmaceutico' },
  { label: 'Jornalista', value: 'jornalista' },
  { label: 'Contador', value: 'contador' },
  { label: 'Cientista', value: 'cientista' },
  { label: 'Policial', value: 'policial' },
  { label: 'Motorista', value: 'motorista' },
  { label: 'Chef de Cozinha', value: 'chef_cozinha' },
  { label: 'Vendedor', value: 'vendedor' },
  { label: 'Piloto', value: 'piloto' },
  { label: 'Fisioterapeuta', value: 'fisioterapeuta' },
  { label: 'Técnico de Informática', value: 'tecnico_informatica' },
  { label: 'Carpinteiro', value: 'carpinteiro' },
  { label: 'Eletricista', value: 'eletricista' },
  { label: 'Mecânico', value: 'mecanico' },
  { label: 'Bombeiro', value: 'bombeiro' },
  { label: 'Esteticista', value: 'esteticista' },
  { label: 'Publicitário', value: 'publicitario' },
  { label: 'Agente de Viagens', value: 'agente_viagens' },
  { label: 'Assistente Social', value: 'assistente_social' },
  { label: 'Garçom', value: 'garcom' },
  { label: 'Nutricionista', value: 'nutricionista' },
  { label: 'Bibliotecário', value: 'bibliotecario' },
  { label: 'Segurança', value: 'seguranca' },
  { label: 'Tradutor', value: 'tradutor' },
  { label: 'Biólogo', value: 'biologo' },
  { label: 'Economista', value: 'economista' },
  { label: 'Geólogo', value: 'geologo' },
  { label: 'Técnico em Radiologia', value: 'tecnico_radiologia' },
  { label: 'Auxiliar Administrativo', value: 'auxiliar_administrativo' },
  { label: 'Técnico em Enfermagem', value: 'tecnico_enfermagem' },
  { label: 'Corretor de Imóveis', value: 'corretor_imoveis' },
  { label: 'Marceneiro', value: 'marceneiro' },
  { label: 'Instrutor de Autoescola', value: 'instrutor_autoescola' },
];
